### ISSUE TITLE
Evaluation du coût du projet

### ISSUE THREAD

**Issue by GuillaumeDubois35** [Pierre-Lemaigre/projet_transverse_equipe_7#22]

**Comment by GuillaumeDubois35** [comment]
Dépôt de l'application sur les stores mobiles
- 25 € pour Google Play
- 99 € / an pour Apple Store

Nom de domaine
- 25€

Hébergement du site web
- 25€/mois (prévision: 2 mois d'hébergement en fin de projet)

TOTAL:
200 €

**Comment by Pierre-Lemaigre** [comment]
Rewieved and Approved
